# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-28 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_financeiro_estrutural_nivel_1', models.SmallIntegerField(default=0, verbose_name='Contador financeiro p/ nivel 1')),
                ('num_financeiro_estrutural_nivel_2', models.SmallIntegerField(default=0, verbose_name='Contador financeiro p/ nivel 2')),
                ('num_financeiro_estrutural_nivel_3', models.SmallIntegerField(default=0, verbose_name='Contador financeiro p/ nivel 3')),
                ('num_marketing_nivel_1', models.SmallIntegerField(default=0, verbose_name='Contador marketing p/ nivel 1')),
                ('num_marketing_nivel_2', models.SmallIntegerField(default=0, verbose_name='Contador marketing p/ nivel 2')),
                ('num_marketing_nivel_3', models.SmallIntegerField(default=0, verbose_name='Contador marketing p/ nivel 3')),
                ('num_pessoas_processos_nivel_1', models.SmallIntegerField(default=0, verbose_name='Contador pessoas p/ nivel 1')),
                ('num_pessoas_processos_nivel_2', models.SmallIntegerField(default=0, verbose_name='Contador pessoas p/ nivel 2')),
                ('num_pessoas_processos_nivel_3', models.SmallIntegerField(default=0, verbose_name='Contador pessoas p/ nivel 3')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'ordering': ['num_financeiro_estrutural_nivel_1'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.EmailField(max_length=254, verbose_name='E-mail adicionado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Controle',
                'verbose_name_plural': 'Controles',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(default=0, verbose_name='ID do usuário enviado')),
                ('email_usuario', models.EmailField(default='email@email.com', max_length=254, verbose_name='E-mail do usuário enviado')),
                ('media_Financeiro_Estrutural', models.FloatField(default=0, verbose_name='Média do envio das perguntas sobre Financeiro/Estrutural')),
                ('media_Marketing', models.FloatField(default=0, verbose_name='Média do envio das perguntas sobre Marketing')),
                ('media_Pessoas_Processos', models.FloatField(default=0, verbose_name='Média do envio das perguntas sobre Pessoas/Processos')),
                ('nivel_Financeiro_Estrutural', models.IntegerField(default=0, verbose_name='Nível do envio das perguntas sobre Financeiro/Estrutural')),
                ('nivel_Marketing', models.IntegerField(default=0, verbose_name='Nível do envio das perguntas sobre Marketing')),
                ('nivel_Pessoas_Processos', models.IntegerField(default=0, verbose_name='Nível do envio das perguntas sobre Pessoas/Processos')),
                ('resposta_pergunta_1', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 1')),
                ('resposta_pergunta_2', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 2')),
                ('resposta_pergunta_3', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 3')),
                ('resposta_pergunta_4', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 4')),
                ('resposta_pergunta_5', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 5')),
                ('resposta_pergunta_6', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 6')),
                ('resposta_pergunta_7', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 7')),
                ('resposta_pergunta_8', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 8')),
                ('resposta_pergunta_9', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 9')),
                ('resposta_pergunta_10', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 10')),
                ('resposta_pergunta_11', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 11')),
                ('resposta_pergunta_12', models.IntegerField(default=1, verbose_name='Resposta para a pergunta de id 12')),
            ],
            options={
                'verbose_name': 'Dado',
                'verbose_name_plural': 'Dados',
                'ordering': ['nivel_Financeiro_Estrutural'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentos', models.CharField(choices=[('Financeiro/Estrutural', 'Financeiro/Estrutural'), ('Marketing', 'Marketing'), ('Pessoas/Processos', 'Pessoas/Processos')], default='Financeiro/Estrutural', max_length=50)),
                ('text', models.TextField(verbose_name='Questão')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['segmentos'],
            },
        ),
    ]
