# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_10_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 10'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_11_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 11'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_12_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 12'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_1_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 1'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_2_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 2'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_3_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 3'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_4_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 4'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_5_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 5'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_6_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 6'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_7_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 7'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_8_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 8'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_1',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 1 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_10',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 10 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_2',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 2 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_3',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 3 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_4',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 4 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_5',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 5 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_6',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 6 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_7',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 7 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_8',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 8 p/ pergunta 9'),
        ),
        migrations.AddField(
            model_name='contadores',
            name='num_pergunta_9_resposta_9',
            field=models.SmallIntegerField(default=0, verbose_name='Contador resposta 9 p/ pergunta 9'),
        ),
    ]
