# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-14 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20171129_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_form', models.TextField(blank=True, verbose_name='Descrição para o Formulário')),
                ('message_register', models.TextField(blank=True, verbose_name='Descrição para o Cadastro')),
            ],
            options={
                'ordering': ['message_form'],
                'verbose_name_plural': 'Descrições',
                'verbose_name': 'Descrição',
            },
        ),
    ]
